service: tesseract-ocr-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'prod'}
  region: ap-southeast-1

functions:
  handler:
    name: tesseract-ocr-service-handler
    description: Performs OCR on an image hosted at a URL and returns its text
    handler: dist/ocr.ocr
    events:
      - http:
          path: /ocr
          method: get
    memorySize: 1536
    timeout: 20

plugins:
  - serverless-offline
